### ISSUE TITLE
Medically Benefitted Drugs 

### ISSUE THREAD

**Issue by reevesj2** [CMSgov/price-transparency-guide#100]
Are Medically Benefitted Drugs to be included in our IN Network rate file or Prescription Drug file?  We do not pay by or store NDC for these drugs, we utilize CPT/HCPC on a fee schedule.

**Comment by BobSyracuse** [comment]
We are assuming any medical drugs will be included along with our In-Network rate file and not our Prescription Drug file since they will be based on CPT/HCPC.
