### ISSUE TITLE
Incorrect required fields on in-network-rates.json and in-network-rates.xml

### ISSUE THREAD

**Issue by rakeshkatte** [CMSgov/price-transparency-guide#116]
Couple of small corrections required.

On the Json schema it should be:
"required": ["negotiation_arrangement", "name", "billing_code_type", "billing_code_type_version", "negotiated_rates" ] 
instead of 
"required": ["payment_type", "name" ]

On the XML schema it should be:
<required>negotiation_arrangement</required> 
instead of 
<required>payment_type</required>

**Comment by shaselton-usds** [comment]
Thanks, @rakeshkatte! Updates can be found here: https://github.com/CMSgov/price-transparency-guide/commit/ee38e0b49d97541155df591c3e56f99e12d8088e
