### ISSUE TITLE
If negotiated rate is based on percentage of charge--then how would this be reported in the in-network file?

### ISSUE THREAD

**Issue by clovis517** [CMSgov/price-transparency-guide#129]
### Discussed in https://github.com/CMSgov/price-transparency-guide/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **tdfow** March 23, 2021</sup>
Since the rate must be published in a dollar amount, how should items/services be represented in the in-network file if based on the percentage of charge?    Would the negotiation type be 'derived'?   How would you report the negotiated rate in the file, since it varies on charge for the item/service?  Or do these items/services get reported?  </div>

**Comment by umangelia** [comment]
Any new updates on how % of billed charges is being reported in the schema?  I saw in comments a note that perhaps it would be acceptable to report a % instead of a dollar amount - but did the schema change to accommodate this?

**Comment by tdfow** [comment]
@umangelia I have not seen any updates on this topic.   The rate must be published as a dollar amount.  Since there is not a claim that has the charge amount, I have heard some will post the rates based on a dollar charge.  There should be a change to either add a new allowed value for the negotiated type as 'percentage of charge' or have something in the schema to provide the 'basis amount'

**Comment by tulsin108** [comment]
Hi Team, do we have any updates/new direction from CMS on this issue? 

Would really appreciate and input/guidance here as soon as possible!! Thanks!

See below from conversation thread in #23:

" [@shaselton-usds](https://github.com/shaselton-usds)
Any updates on the posted of the payment method = % of billed charges? The discussion propose using the average amount paid from claim history of the item/service but this wouldn't be accurate.
A recommendation is to add another value to be used with the negotiated type.
"negotiated_prices":[{
"negotiated_type" : "percent_charge",
"negotiated_rate" : 75,
"expiration_date" : "2022-12-31",
"service_code" : [ "10"],
"billing_class" : "professional"

I completely agree [@Ginger228](https://github.com/Ginger228) - this would be the ideal solution for this problem. We cannot control what providers bill, so when our agreement with them is to pay a percentage of billed charges, without a claim to refer to - we cannot product a dollar amount for the In Network Rates file. I think your suggestion is the best solution to this problem. If we could provide what the contracted percent of billed rate is, then a consumer could potentially reach out to the provider to ask what they would normally bill the insurer for the service. Hospitals are supposed to be publishing their charges anyways per the Hospital Price Transparency mandate.
Also, as you stated, the idea of using an average paid amount from claims history would not be accurate and would therefore be misleading to consumers, which is the opposite of the intent of this mandate. Providers can bill whatever they want for any given service, so to come up with an average billed amount for a service would not only add complexity to the technical solution, but would not be accurate, as you stated.
Without a solution to this problem, I am afraid many plans will be non-compliant with the MRF mandate when it comes to reporting dollar amounts for percentage of billed negotiated rates.
[@shaselton-usds](https://github.com/shaselton-usds) could we please get further guidance from CMS on this issue? Could this issue please be escalated and addressed soon?
I know that many plans whom are part of the Blues Association or who are using vendors need to start finalizing technical solutions and begin generating test files well before July 1st. "

**Comment by clovis517** [comment]
[Update](https://github.com/CMSgov/price-transparency-guide/pull/393)

**Comment by shaselton-usds** [comment]
PR included a way to disclose under percentage of billed charges arrangements: https://github.com/CMSgov/price-transparency-guide/pull/393
