### ISSUE TITLE
Typo in the About text on this repo

### ISSUE THREAD

**Issue by CH-HaroldShort** [CMSgov/price-transparency-guide#134]
This should say `tri-departmental` instead of `tri-deparmental` (missing a `t`).
![image](https://user-images.githubusercontent.com/33648346/124011617-11fbc800-d995-11eb-881a-2fef6fe910e1.png)

**Comment by shaselton-usds** [comment]
@CH-HaroldShort where are you seeing this?

**Comment by CH-HaroldShort** [comment]
@shaselton-usds in the About box on the right side of the main repo [page](https://github.com/CMSgov/price-transparency-guide)
![image](https://user-images.githubusercontent.com/33648346/124836956-c028e400-df38-11eb-8a62-5d631eb5c2cb.png)

**Comment by shaselton-usds** [comment]
oof! Thanks. Fixed.
