### ISSUE TITLE
Schema is missing newly added billing code types

### ISSUE THREAD

**Issue by tdfow** [CMSgov/price-transparency-guide#135]

**Comment by shaselton-usds** [comment]
Thanks @tdfow -- really appreciate it.

Fixes provided here: https://github.com/CMSgov/price-transparency-guide/commit/8305afb167d70d01aac7d0ee086df5d389013687 and https://github.com/CMSgov/price-transparency-guide/commit/0b8d6de3dd295e2dc77caf9980d4d755e7e0b8ac
