### ISSUE TITLE
Different rates by location such as State or Zip Code

### ISSUE THREAD

**Issue by rgouldkc** [CMSgov/price-transparency-guide#173]
We are a regional PPO network located in the Kansas City metro. Some of our provider contracts have different rates for a given Tax Id based on where services are performed usually separated by State (KS or MO) or Zip Code. The zip code grouping uses regex to denote the zip codes such as: 
66006-66025-6604[45679]-66050-6640[29]-66420-6653[39]-6654[26]-6660[13456789]-6661[012456789]-6662[012456]-66636-66647-66667-66675-66683-66699
I don't see anything in the in-network-rates schema that would allow us to denote that a specific rate was for a State or a Zip code and identify what the state(s) or zip code(s) are the rate applies to.
Anyone have any ideas other than putting something in the In-Network Object description or adding fields to the Negotiated Rate Details object.

**Comment by shaselton-usds** [comment]
Contextual information such as zip code or state can be disclosed in the `additional_information` attribute.
