### ISSUE TITLE
site discoverability/web crawlers/bots

### ISSUE THREAD

**Issue by vtp10** [CMSgov/price-transparency-guide#178]
The Git page provides the following info: 
_Public Discoverability
These machine-readable files must be made available to the public without restrictions that would impede the re-use of that information.

The location of the these URLs must be provided over HTTPS to ensure the integrity of the data.

Robots.txt
To allow for search engine discoverability, neither a robots.txt file nor meta tag on the page where the files are hosted will have rules such that give instructions to web crawlers to not index the page.

This is typically follows the format of <meta name="robots" content="noindex, nofollow"> or for a robots.txt file using the Disallow directive._

**_Question/Clarification:_**

The above information relates specifically to search engine discoverability, but does this mean that "all" web crawlers, bots, etc. should be allowed to access the site & its relevant data without any impediments? Are there any cases where such external agents should not be allowed>

**Comment by shaselton-usds** [comment]
Duplicate: https://github.com/CMSgov/price-transparency-guide/discussions/180
