### ISSUE TITLE
SSNs

### ISSUE THREAD

**Issue by calfred33** [CMSgov/price-transparency-guide#243]
Plans are having trouble determining how to proceed with the requirement to disclose providers TINs in the machine-readable files, given that so many providers use their personal social security numbers as TINs. Guidance from CMS on how to handle this issue would be welcome.

**Comment by shaselton-usds** [comment]
Please look for technical clarification here: cms.gov/healthplan-price-transparency/resources/technical-clarification

Also, a PR addressing this can be found here: https://github.com/CMSgov/price-transparency-guide/pull/264 and here: https://github.com/CMSgov/price-transparency-guide/pull/265
