### ISSUE TITLE
"Description" Data Element for In-Network Negotiated Rates

### ISSUE THREAD

**Issue by Stephanie-Raymond** [CMSgov/price-transparency-guide#280]
For information being reported on the in-network negotiated rates for all items and services, specifically the “Description” data element located under the In-Network Object, please confirm whether this field is indeed 'Optional' as currently defined in the technical guidance or does CMS expect it to be populated whenever information is available in IT systems/database?

Similarly, is it correct to interpret that the 'Billing Code’ under the In-Network Object is intended to mean the Billing Code Description' for this field?

![image](https://user-images.githubusercontent.com/94474475/142049178-a1e70d90-9982-4054-9775-ada9cdd231ad.png)

**Comment by shaselton-usds** [comment]
Cleaning up old Issues. The documentation has been changed to "required"
