### ISSUE TITLE
Formatting "Plan Name" Naming Convention for Multiple Plan Names

### ISSUE THREAD

**Issue by Stephanie-Raymond** [CMSgov/price-transparency-guide#285]
Is ‘Plan Name’ required as part of the MRF naming convention given the recent change allowing a MRF submission for multiple plan names?  Could CMS/Github provide an example of how multiple plan names would be formatted?

**Comment by shaselton-usds** [comment]
Naming requirements can be found [here](https://github.com/CMSgov/price-transparency-guide#file-naming-convention) for organizations that choose to implement a table of contents file.
