### ISSUE TITLE
Questions related to pharmacy data

### ISSUE THREAD

**Issue by ballengeec68** [CMSgov/price-transparency-guide#422]
We have a few questions relating to pharmacy data as there not been much discussion or examples provided for pharmacies.  Can you please provide an example format for the in-network schema that is for pharmacy claims information?  As a PBM, would the carveout of NDC information be at a client level or a book of business level?  For the negotiation rate, are you looking for it through a pharmacy breakdown or a general drug NDC breakdown?  Can you provide further explanation as to what the billing_code_type_version is in reference to for pharmacy claims data?  Would it be something similar to NCPDP?

**Comment by shaselton-usds** [comment]
Duplicate Issues: https://github.com/CMSgov/price-transparency-guide/issues/437 and https://github.com/CMSgov/price-transparency-guide/issues/438
