### ISSUE TITLE
In-Network Schema list 'description' as required, README says it is optional

### ISSUE THREAD

**Issue by olderthandirt5** [CMSgov/price-transparency-guide#427]
Ran a file through the validator and got a notice that 'description' was required.
Output from Validator:

> 
> Input JSON is invalid.
> Error Name: required
> Message: Object is missing the following members required by the schema: 'description'.
> Instance: #/in_network/0
> Schema: #/definitions/in_network

https://github.com/CMSgov/price-transparency-guide/tree/master/schemas/in-network-rates#in-network-object

mint-thompson replied:

> This appears to be a discrepancy between the schema definition, which lists this field as required, and the schema's README file, which lists this field as optional

**Comment by shaselton-usds** [comment]
Sorry about the noise on this. Documentation is fixed. Thank you.
