### ISSUE TITLE
In-Network File README.md Inaccurate Compared to Example in-network-rates-capitation-sample.json

### ISSUE THREAD

**Issue by BobSyracuse** [CMSgov/price-transparency-guide#5]
In the example, there is "capitation_id": "12345", but in the file layout for the In-Network object there is not a Field/Field Name listed for capitation_id or Capitation ID. This question was previously asked by another individual. Is the example incorrect or is the README.md for In-Network File incorrect?

Which is correct to allow the file to be correctly used?

**Comment by shaselton-usds** [comment]
Good catch. 

We have a "name" attribute that is meant to capture the specific arrangement types.

Updates can be found in this checkin: https://github.com/CMSgov/price-transparency-guide/commit/775e81b8792ed847a5475c572efe44eabc5a05b1
