### ISSUE TITLE
Disjoint of version numbers between this site and the CMS Validator

### ISSUE THREAD

**Issue by rgouldkc** [CMSgov/price-transparency-guide#517]
The current version number on this site is 1.0.8. Attempting to validate in-network files against this version number returns an error which lists all the version numbers that are available[CMS-MRF-Validator available(https://github.com/CMSgov/price-transparency-guide/files/8953330/CMS-MRF-Validator.available.version.numbers.txt)
 Also the validator site shows a current version of 1.1.0

When validating our in-network files I specify v1.1.1 which does work. But it is confusing when the available version numbers don't include the one on this site and does include newer version numbers that this sites.

Can we get some explanation as to what the apparent disjoint is?

**Comment by shaselton-usds** [comment]
@rgouldkc There wasn't a tag associated with the v1.0.8. The validator pulls versions off of [available tags](https://github.com/CMSgov/price-transparency-guide/tags). Looks like there might be some tags that were missed. In this case, nothing actually [changed in the schema for v1.0.8](https://github.com/CMSgov/price-transparency-guide/pull/451/files). We'll attempt to tag all merges moving forward even if they are documentation fixes to avoid confusion.
