### ISSUE TITLE
Provider reference location link is not working in example file

### ISSUE THREAD

**Issue by guido-muscioni-anthem** [CMSgov/price-transparency-guide#666]
Hello!

While going trough the `README` for the `in-network-rates` schema, I have noticed that the file referenced by the following line does not contain a valid link to a `provider-reference` object:
https://github.com/CMSgov/price-transparency-guide/blob/2a7d7afa3082ed9e97890888cef539fbbb688a84/schemas/in-network-rates/README.md?plain=1#L89

Here is the line of the file where the link does not work:
https://github.com/CMSgov/price-transparency-guide/blob/574caa73dd0a1f49c7b4696f585dc6f8b087d67a/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json#L27

In the case this is the expected outcome, please close this issue, however, in case this link is supposed to point to a valid `provider-reference` file, then the `raw` version of the example in the `README` could be a candidate: https://raw.githubusercontent.com/CMSgov/price-transparency-guide/master/examples/provider-reference/provider-reference.json

In case, here is a personal branch were I have made the changes (https://github.com/guido-muscioni-anthem/price-transparency-guide/blob/fix/location-in-provider-references-example-file/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json), and I can submit a PR to `develop`. 

Thank you!

**Comment by shaselton-usds** [comment]
@guido-muscioni-anthem The example in sample file was just meant to be an example, not actually link to a real external provider group url.
