### ISSUE TITLE
How do I report BCBS non-compliance?

### ISSUE THREAD

**Issue by cigzigwon** [CMSgov/price-transparency-guide#669]
Trying to work with their files is spiking our costs because they don't follow specification. I'm really tired on waiting hours to get insight to this data. If I'm following the rules then why can't they do it?

I both produce and consume these files and can deal with ALL providers that I'm given including this one. But it's time for the Blue Cross and Blue Shield to comply. What avenues do I have to get the ball rolling on this non-compliant provider.

They are costing everybody. I should be able to pull their index and target the payer I want in 300 milliseconds not 6-8 hours of tying up my most expensive resource. I need to consume all the rates/refs for the state of Illinois and can do it but it costs WAY too much!

I can't even assert if the file is current. They also have non-reporters as the dates lag back to 8-27-2020. So basically what I'm learning is that CMS.gov has absolutely ZERO influence on regulating Blue Cross and Blue Shield.
 
eg. 2023-04_340_46B0_in-network-rates.json

No date. No entity. No payer. ALL FILES.

So what can I do to report this entity that is now ruining my business over my own willingness to comply, this is what we guarantee our clients because we expected BCBS to be a model not a complete failure?

**Comment by dgolden** [comment]
@cigzigwon Chris, thank you for being one of the good guys who are being responsible. 

Should BCBS or other payers wish to improve their compliance, Keyark is available to provide a private assessment. We will walk through your Index/TOC files and report whether the In-Network MRFs can be downloaded. If they can be downloaded, we will check that the MRFs are useable.

TPAs, which have the primary liability for delivery of MRFs for their plans, should also consider use of this Keyark service. Doing so will both protect the TPA from liability and ensure that their payer is fulfilling any contractual agreement to provide useable MRFs.  For TPAs this is an inexpensive audit that can potentially avoid significant fines, should CMS ratchet up its enforcement. 

For both payers and TPAs that are public companies, the exposure to CMS fines should be a real concern for your risk assessment team and merits a note in your financial reports.

**Comment by cigzigwon** [comment]
@dgolden Thanks for the offer but I have all the solutions in place to determine all of those things in Amazon cloud in under an hour. I'm about to get our first bytecount on the throughput of our system here. I expect to be the World Record holder in processing and parsing these things today so nothing you can offer is needed. I need a regulator to order whats mandatory as of Jan 1, 2023 because I have spent the last four months incurring costs where I don't have to if the reporter was compliant.

I ABSOLUTELY expect BCBS to be fully compliant or to be hit with compliance. They are indeed in non-compliance. So it needs to be cited or penalized. We need enforcement not insight.

**Comment by cigzigwon** [comment]
@dgolden You can get back to me when you guys can handle this case for use in under 2 hours against CIGNA's OAP/PPO. Until then I would not consider that Keyark is going to be able to provide me any productivity gain when I've personally harvested and processed/imported about 2.2 PetaBytes of this data. I'm the exception in your potential clientele base.

**Comment by dgolden** [comment]
@cigzigwon Impressive processing!  We do handle external location files but I have no idea how long it takes. How long did it take for you to digest all the Cigna OAP/PPO?  How many MRFs is that? 

Academics are looking for data for research purposes.  Are you open to sharing your data?
For the record I am not an academic, and I am not looking to tap into your data.

**Comment by angelamarie0975** [comment]
Yes I had to use my personal one to sign up for it. Sent from my iPhoneOn Apr 14, 2023, at 2:38 PM, David M Golden ***@***.***> wrote:﻿
@cigzigwon Chris, thank you for being one of the good guys who are being responsible.
Should BCBS or other payers wish to improve their compliance, Keyark is available to provide a private assessment. We will walk through your Index/TOC files and report whether the In-Network MRFs can be downloaded. If they can be downloaded, we will check that the MRFs are useable.
TPAs, which have the primary liability for delivery of MRFs for their plans, should also consider use of this Keyark service. Doing so will both protect the TPA from liability and ensure that their payer is fulfilling any contractual agreement to provide useable MRFs.  For TPAs this is an inexpensive audit that can potentially avoid significant fines, should CMS ratchet up its enforcement.
For both payers and TPAs that are public companies, the exposure to CMS fines should be a real concern for your risk assessment team and merits a note in your financial reports.

**Comment by cigzigwon** [comment]
Apparently nobody is regulating this. It's a free for all. Some have SFTP based MRFs with not FQDNs for location in provider groups so those files are useless. Most naming conventions are not to specification and the list goes on!

And then CIGNA uses that same feature to link to "quark sized" files. I think the point of linking to "provider_groups" was for the sake of housing large data.  Just doesn't make sense! It takes longer for me so what they are doing adds no value to the consumer.

I would first say the individual groups file schema is missing something. Perhaps a parent identifier? Since you don't have the "reporting_entity_name" as metadata there, I have to do some funky stuff. It's a waste of time to concoct some archaic folder system to download those files when I'm HTTP-Stream parsing them as they come into memory.

July 1st 2022 is long gone. Where is my regulation? Why am I suffering and taking a back seat to the giant insurance providers? I have one of the best solutions in the USA for publicizing this data. I'm sure of it. Please advise as I'm personally paying for their violations to please my partners/clients.

**Comment by cigzigwon** [comment]
@dgolden Stop trying to get something out of me. Now that I know what your company does I'd say you guys are going to be in a bit of trouble. I may just decide to start off by replacing your MRF Explorer w/something that actually works against large compressed files and gets you what you want in "actual minutes". You need to be able to handle much larger files than your sample set in the tool.

All I have to do is make my own and point it to some 24GB compressed files and see if you guys can beat me? Doubts.

**Comment by dgolden** [comment]
@cigzigwon 
The samples are provided so there is a data set that matches the PDF tutorials, necessary as a payer may archive their MRF. 

Users can enter a URL to any MRF on the web.  We do process extremely large (when uncompressed) MRFs. The process takes longer, as you'd expect, so enjoy some coffee or handle some email while the process is underway.

Sorry to have raised your blood pressure. I do admire your passion. It would be wonderful if we can get the State insurance commissions to develop a similar passion towards data transparency. If the word went out that rate increases will not be considered until payers fulfill the CMS mandate, we would see much better behavior.

**Comment by cigzigwon** [comment]
@dgolden I apologize too as I should be sleeping but can't because one of our provisioners has not yet been able to acquire the IT staff to move away from SFTP which is ultimately a sale for Pyroclastic as we will enable them to export their relational data so that we can help them build/host their MRFs in cloud.

As a jack of all trades I've learned to adapt quickly and now my adaptation is a core-competency of my business. I think the mistake I made was jumping in a bit early not know this federal mandate would not be enforceable OR lagging/tied up.

The reality is that I now have to eat the costs in terms of turn around time of development due to making many exceptions due to the lack of compliance globally. I would like to commend companies such as CIGNA and United Healthcare as they seem to be the only companies who house the IT staff so that I'm not inheriting the costs. The highest cost we see is in processing time in an AWS "compute machine". It is really up longer than it needs to be. My limitation is that I need to run QA in that environment because I can't possibly mirror that server's performance and churn through the "large file cases" and yield a PASS/FAIL state before doing an entire run for each month.

I really appreciate you not giving up on me David as you have shown there is "business intelligence" in America. At Pyroclastic we are trying to prepare for 2024 while other IT consulting based firms lag back to 2011 because they simply employ low-quality inexperienced developers. I'm sorry if I seem overly competitive but I would still like to demo what I can do w/my own "free" version running in DigitalOcean's Cloud SaaS "infra-ware". My hope is that you see an opportunity if you aren't currently employing "Hypertext streaming data services". It's not the first technology of it's kind but we write software for systems that are "truly concurrent" and strict adherence to "Von Neumann" pattern.

I apologize again as I'm always "in the trenches" so to speak and get really annoyed by "sales guys". I do note your experience and know how and to be honest have "the best" publicly available tool for inspection of the MRF ATM. I do commend your company for this. My tool is only available via CLI and I would like to test our 176GB INN MRF but unfortunately cannot supply the link as I do not want to reveal my client's business. Especially to the sales team of a larger company. Sorry. I'm smart too. I would send the URLs to myself so I can have all my test cases lined up to perfect this softtware(s). Nice work!

**Comment by mfrobben** [comment]
Gents - file your complaints here: https://mats.secure.force.com/pt 

There's a formal review and tracking process for noncompliance. If you'd like help understanding the BCBS state and network code system and their network reciprocity rules, happy to help. Highmark and other BCBS entities have crosswalk tables I can point you to.

**Comment by dgolden** [comment]
It's great to see a Y Combinator company engage in price transparency: https://www.ycombinator.com/companies/serif-health

Great web site and product/service offerings as well:
https://www.serifhealth.com/

Are you seeing payers improving their MRF production in response to complaints?

**Comment by cigzigwon** [comment]
@mfrobben I've been looking for this link and was about to report several things at one point. That number has now doubled. Basically all providers are non-compliant (90%) in their file based reports as of next week.
