### ISSUE TITLE
Data from the provider Medica is partially not accessible

### ISSUE THREAD

**Issue by usatenko** [CMSgov/price-transparency-guide#697]
I see a list of files here, actually, Medica has links to this storage, but the files are not accessible:
https://transparency-in-coverage.optum.com/?file=CMC_Transplant_MRRF.json&origin=oh
```
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:1004b309-801e-002f-472b-c692a3000000 Time:2023-08-03T16:58:24.1665631Z</Message>
</Error>
```
Has anyone solved this problem somehow?

**Comment by shaselton-usds** [comment]
Closing due to this not being a TiC schema issue.
