### ISSUE TITLE
Errors during Cigna file processing

### ISSUE THREAD

**Issue by ks121980** [CMSgov/price-transparency-guide#728]
Has anyone else run into the following issues when trying to process Cigna files:

403 error: https://priorityhealthtransparencymrfs.s3.amazonaws.com/2023_12_01_priority_health_PPO_in-network-rates.zip?Expires=2022019199&Signature=qOfsLuyfX~qWjNn95rhIHcNyCeFzaDG-0lasNKU81FqnmXp7~Z5uL9QpblzN1wdR8RlxpzgXivR9SQAJG19AosPoRPVfnFJhT~A5SccpsYx2tY7qqAHkLmSgrTsuwuXDOq3pC48jdclr1YDIBEgMrBBfO4UDXujWFJUZoTyhS8Hwhn1RJkCVjQnpP6-BgxH8DvQLkS3x-t--G85Wv7dxdNIF-BR1TWPnTxoXZO6LOq1urk-lgFP~FUoYKS0lq~~RgHdSXGkJ5jg1DHeJgUnZGAVT5gNs31q5qL9SugS6pJmMY5crx6gpJDJSoP7DMktz9Vcd1d~XRAaWiql9d-gEIQ__&Key-Pair-Id=K1NVBEPVH9LWJP

404 error: 
Link 1: https://mrf.healthsparq.com/mvp-egress.nophi.kyruushsq.com/prd/mrf/MVP_I/MVP/2023-12-01/inNetworkRates/2023-12-01_CIGNA_MVP-Health-Care,=-Inc.json.gz?Expires=2022019199&Signature=YElKFjLATYwo6PVbM4MP~v5EZS~cEh8OUlOoGMTFB4P0Nw--V7JBZI4hteMh~pzLMRy3J3jALdnJDHpW~zB5kWg899VgVVm1X3WxszYZm6eZ6LGBeE9j1b2DkfiQOIoNrM7SzJ1vp3i6kglD4EZlKqBlh2vwMo3euTCQrq6GlTnsAWDgW~-GdtOT8a39pLZk24HeG4CZYlX1kGlqW8c8wbmvEy7thVowor-8XAPffiTEQfWc5WbOPdDg-K9LKrT82o6V9ZgzQcQL6PZHOsRxWfyT55a7m42QVhqTvLo7YwhLSEaDMOjCgTWWiuwSxgQmkonZTSFVrEPRkdFWc9uDqQ__&Key-Pair-Id=K1NVBEPVH9LWJP

Link 2: https://eusprdtransparencymrfp32.blob.core.windows.net/thp/CarelinkNetwork_INN_202312.zip?Expires=2022019199&Signature=QlNdrIq66ShUIju-Xt9yT6MapX9jIX7Pq2yeBcSoUVZtsiQWt0pnvmHAyRCJIr3XVrWBQmsV4WSNol9uAyB1KoNE9HZg2in-XrU9uWq8OXz7C12SSfl8FAhTV8V8ThOVRytSflxbRf-eH2B1F77q-BWzEizGBaEkpN38SfTWhCdGQcB0e0~nBfeJO0UmjhHxFw7895f30as2VKinv2dkEuiF8~uoJYQdxtU4CajqQJuBN4l0IfFoGckggsaFdl-TsuWFK1SLTvh7wmBkNT8iwjzG7nyMNI5Z0uKOqf9qm1e9KkrKW9Umajp~Ux3~lNvHLkULU7o6BxOkmCqIGtUPDA__&Key-Pair-Id=K1NVBEPVH9LWJP

**Comment by DisapprovingDad** [comment]
Having the same issues with these files
