### ISSUE TITLE
Output is not showing valid/invalid when trying to validate JSON

### ISSUE THREAD

**Issue by winnkathy-hub** [CMSgov/price-transparency-guide#748]
Hello.
For some reason the output when trying to validate a JSOn file through docker is not appearing in the cmd screen.  I see the "info running validator container" but nothing else.

I even tried it on the invalid file sample and it still didn't work.   Can someone please help me with this issue?

Thanks.

**Comment by shaselton-usds** [comment]
@winnkathy-hub Assuming that you're still running into issues, can you please start a discussion or issue over at the validator repository? Thanks!
