### ISSUE TITLE
Zipped files for CMS Validation

### ISSUE THREAD

**Issue by Causink11** [CMSgov/price-transparency-guide#751]
These news files in the changed format for 2024 have been massive, over 4GB. Can the CMS validator tool accept a zipped file?

**Comment by JR-CMS** [comment]
You can use the validator for a ZIP archive that contains a JSON file. If multiple JSON files are found within the ZIP archive, you can choose which one you want to validate. You can read more here: https://github.com/CMSgov/price-transparency-guide-validator?tab=readme-ov-file#validate-a-file-at-a-url

**Comment by shaselton-usds** [comment]
I'll just follow up with @JR-CMS and recommend with gzip or zip compressions. While the validator can process both zip and gzip extensions, it is usually is less complex to process a gzip file due to there only be a single file to validate.
