### ISSUE TITLE
Cannot find Schema version

### ISSUE THREAD

**Issue by WizardJosh** [CMSgov/price-transparency-guide#756]
Could not find a schema version named "1.0.0". Available versions are: ...
Ran this on all of my files which are version 1.0.0 ... Ran this on the supplied 
test-files/in-network-rates-fee-for-service-sample.json with the same error. I am pretty sure i built this correctly.
What am i doing wrong here?

**Comment by shaselton-usds** [comment]
@WizardJosh If you're looking for what the v1.0.0 release was, you can find it [here](https://github.com/CMSgov/price-transparency-guide/releases/tag/v1.0.0).
