### ISSUE TITLE
Drug Type of Measurement Valid Values

### ISSUE THREAD

**Issue by LJTempleton** [CMSgov/price-transparency-guide#758]
We are looking ahead to the 01/01/2025 Hospital Price Transparency requirements.  The table provided in the GitHub data dictionary for drug type of measurement shows two valid entries for gram and grams.  

![image](https://github.com/user-attachments/assets/671194f5-153d-47ec-85a5-62a8b6a1c2ca)

Is the GM value for micrograms, a common pharmacy unit?  If so could the table be updated?  If not, could clarifying language be added to differentiate the two values?  

This question has also be submitted to CMS.

**Comment by shaselton-usds** [comment]
@LJTempleton Thank you for the question. Questions/information regarding the hospital price transparency can be found [here](https://github.com/CMSgov/hospital-price-transparency).
