### ISSUE TITLE
OON allowed amounts example does not match schema definition

### ISSUE THREAD

**Issue by jkauflin** [CMSgov/price-transparency-guide#80]
Schema for OON Allowed Amounts says tin is a string:  **"tin": { "type": "string" },**
But in your examples, you have a number (integer) value:
 "allowed_amounts": [
        {
          "tin": 1234567890,

**Comment by BobSyracuse** [comment]
In the file examples for Prescription Drug and In-Network Rates the examples include a "-" although a TIN is a 9 numeric value
<tin>22-2222222</tin>

The NDC is listed in the Prescription Drug schema as a String although it is a 10 digit value
"ndc": "16729-004",

**Comment by jkauflin** [comment]
After getting the JSON schema validation working, I realize the schemas don't match the examples in several places (different field names and types, etc.) - Is this intentional to show that schema validation is working?  Which is correct - the examples or the schema?

**Comment by BobSyracuse** [comment]
@jkauflin I have been using the schema itself as for what is considered "correct". There have been other items that have been cleaned up over the months between the schema and the examples.

**Comment by shaselton-usds** [comment]
@jkauflin Thanks for the catch. Updated here: https://github.com/CMSgov/price-transparency-guide/commit/ee6fd8f71b08e000472f684500faeaef314b157d

The schema is the source of truth. The examples are being provided to help out with common scenarios -- and, as @BobSyracuse pointed out, are being cleaned up when discrepancies are found.
