### ISSUE TITLE
8 Digit NDC Issue

### ISSUE THREAD

**Issue by atw1223a** [CMSgov/price-transparency-guide#94]
The prescription drug schema indicates that NDC reporting for prescription drugs should be done at the 8 digit level as the last two digits of an NDC are for package size/quantity. In looking into this further, for example, NDC 000740124 for Humira. The first 8 digits of the NDC are the same for Humira Pen Peds, Humira Pen Kit, Humira Pen 80/0.8ml, Humira Pen Kit CD/UC/HS. While each product has the same first 8 digits, the prices differ between the products. How do we determine which drug to select when each NDC is slightly different in price at the 10 digit level?

Another example is Cosentyx. The NDC 000780639 is used for both the 300 dose pen, 150 mg/ml pen, the 150 mg/ml pen, and the 300 dose. The price differs significantly depending on which full 10 digit NDC is used.

How do we convert an 10 or 11 digit NDC to 8 digits? When an NDC is in the 5-4-2 format (ID Format Code 6 on the Medispan File), we would be dropping the last digit of the product code. Moreover, how do we convert an 11 digit NDC to 8 digits where the ID Type Code is 1 and the ID Format Code is 1, 2, 3, or 6?

**Comment by CH-HaroldShort** [comment]
It seems that NDCs should always be normalized to the full 11 digits, that way the first 9 digits could always be used without ambiguity or running into the issues described here.

**Comment by bryanbriegel** [comment]
The rule indicates 10/11 byte NDC is required. "The NDC, in contrast, is a unique 10-digit or 11-digit
3-segment number, which provides a universal product identifier for drugs in the United States. The three segments of the NDC identify: The labeler (any firm that manufactures the drug); the product (specific strength, dosage form, and formulation of a drug); and the commercial package size and types" // re why not use RxCUI.  Also: "plans and issuers may only use the NDC as the billing code type because, as discussed later in this preamble, the accuracy of pricing information for prescription drugs requires precise and specific product information, including package size and manufacturer.."

**Comment by CH-HaroldShort** [comment]
Note on NDC from [here](https://www.govinfo.gov/content/pkg/FR-2020-11-12/pdf/2020-24591.pdf), on page 65:
> In the preamble to the HIPAA regulations,
> HHS stated that it was adopting a uniform 11-digit
> format to conform with customary practice used in
> computer systems (65 FR 50314, 50329). (Aug. 17,
> 2000). The HIPAA 11-digit NDC format is
> standardized such that the labeler code is always
> 5 digits, the product code is always 4 digits, and
> the package code always 2 digits. To convert a 10-
> digit NDC to an 11-digit HIPAA standard NDC, a
> leading zero is added to the appropriate segment to
> create the 11-digit configuration as defined above.
> See 83 FR 38666 (Aug. 7, 2018).

**Comment by ltopor** [comment]
Is the consensus that we should follow the rule, which specifies 10 or 11 digit NDCs be used, and not the schema which calls for 8 digits and will cause confusion?  Can someone from HHS please weigh in and provide clarification?

**Comment by Brinkley100** [comment]
If we do the reporting at the NDC 8 or 9 level, can CMS please establish standardized  business rules to compute pricing if the pricing varies at the NDC 9 level? 
What is every else doing  in the absence of standardized business rules? Are you averaging out the AWP prices across all NDC11s that make up the NDC9 or are you dropping outliers that will skew the pricing and averaging out the majority at an  NDC9 level? Any other ideas?
